### ISSUE TITLE
Some initializing error

### ISSUE THREAD

**Issue by deanh2k** [gcflymoto/LendingClub#3]
Looks like some kind of parse/initialization error.
Has formatting changed?

Downloading: LoanStats3c.csv.zip
Worker[-1] Initializing from LoanStats3a.csv inside LoanStats3a.csv.zip ...
Error in row 3
    mths_since_last_delinq:
    inq_last_6mths: 1
    grade: B
    annual_inc: 24000
    total_acc: 9
    out_prncp: 0.00
    emp_length: 10+ years
    total_pymnt: 5861.071414249
    out_prncp_inv: 0.00
    pub_rec: 0
    revol_util: 83.7%
    total_rec_prncp: 5000.00
    earliest_cr_line: Jan-1985
    delinq_2yrs: 0
    open_acc: 3
    dti: 27.65
    purpose: credit_card
    addr_state: AZ
    desc:   Borrower added on 12/22/11 > I need to upgrade my business technolog
ies.<br>
    term:  36 months
    total_rec_int: 861.07
    installment: 162.87
    int_rate:  10.65%
    funded_amnt: 5000
    loan_status: Fully Paid
    home_ownership: RENT
    issue_d: Dec-2011
Traceback (most recent call last):
  File "lcbt.py", line 834, in <module>
    sys.exit(main())
  File "lcbt.py", line 790, in main
    lcbt.initialize()
  File "lcbt.py", line 534, in initialize
    self.test.get_loan_data().initialize()
  File "C:\Users\Dean\Dropbox\Genetic Algorithm\LendingClub-master\LendingClub-m
aster\py\LoanData.py", line 67, in initialize
    self.load_data()
  File "C:\Users\Dean\Dropbox\Genetic Algorithm\LendingClub-master\LendingClub-m
aster\py\SqliteLoanData.py", line 24, in load_data
    LoanData.LCLoanData.load_data(self)
  File "C:\Users\Dean\Dropbox\Genetic Algorithm\LendingClub-master\LendingClub-m
aster\py\LoanData.py", line 107, in load_data
    self.parse_lc_csv(csv_reader, loans, loans_info)
  File "C:\Users\Dean\Dropbox\Genetic Algorithm\LendingClub-master\LendingClub-m
aster\py\LoanData.py", line 134, in parse_lc_csv
    loan, loan_info, parsed_loan_ok = self.normalize_loan_data(raw_loan)
  File "C:\Users\Dean\Dropbox\Genetic Algorithm\LendingClub-master\LendingClub-m
aster\py\LoanData.py", line 214, in normalize_loan_data
    raw_loan[conversion_filters[LOAN_ENUM_income_validated].name])
KeyError: 'is_inc_v'

**Comment by cflannagan** [comment]
Getting the same error. Since it's occurring on row 3, I guess something in that row tripped something, but I don't know enough python to determine what the issue is.
